# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Tax Calculator

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.8'

    - name: Install Dependencies
      run: make deps

    - name: Build
      run: make build

    - name: Linter
      run: make lint

    - name: Test
      run: make test
